export const copy = {
  appTitle: "Kickdraw",
  appDescription:
    "A cleaner Kick giveaway and raffle console for live chat draws.",
  connectEyebrow: "Kick chat raffle control",
  connectTitle: "Run clean Kick raffle draws from one control room.",
  connectDescription:
    "Connect a channel slug, bring chat live, and run weighted giveaway draws with local-only settings and winners.",
  channelLabel: "Kick channel slug",
  channelPlaceholder: "xqc",
  connectButton: "Connect channel",
  connectingButton: "Loading channel…",
  landingFeatureRolesTitle: "Badge-aware filters",
  landingFeatureRolesText:
    "Gate entries by subscriber, moderator, VIP, OG, and founder badges when Kick chat exposes them.",
  landingFeatureDrawsTitle: "Stream-ready draw flow",
  landingFeatureDrawsText:
    "Weighted draws, custom animations, and winner confirmation.",
  landingFeatureMemoryTitle: "Per-channel memory",
  landingFeatureMemoryText:
    "Reconnect to a slug and pick up stored settings and winner history without dragging state across channels.",
  connectErrorPrefix: "Connection error",
  chatStatusLive: "Live capture",
  chatStatusWaiting: "Stand by",
  chatStatusLost: "Connection lost",
  controlDeck: "Settings",
  liveGiveaway: "Giveaway",
  resultsRail: "Winners",
  entryRulesSection: "Entry rules",
  audienceFiltersSection: "Audience filters",
  drawBehaviorSection: "Draw behavior",
  keywordLabel: "Keyword",
  recentChatCutoffLabel: "Active chat window",
  winnerCountLabel: "Winner count",
  subscriberFilterLabel: "Subscribers",
  moderatorFilterLabel: "Moderators",
  vipFilterLabel: "VIPs",
  ogFilterLabel: "OGs",
  founderFilterLabel: "Founders",
  audienceModeAny: "Allow all",
  audienceModeInclude: "Include only",
  audienceModeRequired: "Required",
  audienceModeExclude: "Exclude",
  multiplierLabel: "Multiplier",
  followLengthLabel: "Minimum follow age",
  subLengthLabel: "Minimum subscription length",
  spinDurationLabel: "Spin duration",
  winnerClaimLabel: "Winner confirmation",
  claimDurationLabel: "Claim window",
  animationLabel: "Draw animation",
  animationWheel: "Name Spinner",
  animationSlotMachine: "Slot Machine",
  animationCharScramble: "Char Scramble",
  startGiveawayButton: "Start giveaway",
  resetSessionButton: "Reset session",
  drawButton: "Draw winners",
  participantsTitle: "Participants",
  waitingStatus: "Start giveaway to connect to chat.",
  connectedStatus: (keyword: string) =>
    keyword === ""
      ? "Any chat message enters the raffle."
      : `Listening for "${keyword}".`,
  lostStatus: "Chat disconnected.",
  connectViewFooter:
    "No backend. No server-side persistence. Giveaway data stays in your browser.",
  headerChangeChannel: "Change channel",
  headerClearData: "Clear all data",
  clearDataTitle: "Clear all persisted data?",
  clearDataDescription:
    "All saved settings and winner history for every channel will be removed from local storage.",
  changeChannelTitle: "Leave this channel?",
  changeChannelDescription:
    "The live session will be reset and you will return to channel connect.",
  cancel: "Cancel",
  continue: "Continue",
  claimTitle: "Winner Confirmation",
  claimPending: (winner: string, seconds: number) =>
    `${winner} must confirm in chat within ${seconds}s.`,
  claimConfirmed: "Winner confirmed.",
  claimFailed: "Winner did not confirm in time.",
  claimAcknowledge: "OK",
  drawPendingTitle: "Checking candidates",
  checkingCandidate: (name: string) =>
    `Checking ${name} against follow requirements…`,
  drawNoParticipants:
    "There are no valid participants left in the current draw pool.",
  drawFollowCheckError: "Follow duration check failed. The draw was cancelled.",
  claimChatEmpty: "No confirmation message yet.",
  overlayEmptyChat: "Waiting for winner chat…",
  followerBadge: "FOLLOWER",
  subscribersBadge: (count: number) => `Subscriber x${count}`,
  moderatorBadge: "MOD",
  vipBadge: "VIP",
  ogBadge: "OG",
  founderBadge: "FOUNDER",
  monthsShort: "mo",
  minutesShort: "min",
  daysShort: "days",
  secondsShort: "sec",
  anyMessage: "Any message",
  noWinners: "No winners yet.",
  noParticipants: "No participants yet.",
  mobileSettings: "Settings",
} as const;
